name = "OpenTelemetryUber"
uuid = "463ee90e-87a9-4aee-9dc9-6a5c2417ebf4"
authors = ["Jun Tian <tianjun.cpp@gmail.com>"]
version = "0.1.0"

[deps]
OpenTelemetryAPI = "4f63ef3d-5940-44e7-a611-2d97696cffc9"
OpenTelemetryExporterOtlpProtoGrpc = "83e8ae56-efb3-499e-9158-b649d4f902fc"
OpenTelemetryExporterPrometheus = "34e26579-e93c-4b5e-ba07-7afb633408c2"
OpenTelemetryProto = "cc651e92-2989-4f95-bcc3-32e6fb6ac025"
OpenTelemetrySDK = "f5929ecf-be04-446c-b2f2-494e1fe70ee4"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
OpenTelemetryAPI = "0.2"
OpenTelemetrySDK = "0.2"
OpenTelemetryExporterOtlpProtoGrpc = "0.2"
OpenTelemetryExporterPrometheus = "0.1"
OpenTelemetryProto = "0.13"
Reexport = "1"
julia = "1"
